import { useEffect, useRef } from "react";
import Plotly from "plotly.js-dist-min";

// The complete taxonomy data - MASSIVELY expanded with cutting-edge 2024-2025 components
const taxonomyData = [
  { id: "aac:tax-1.0", label: "1.0 Cognitive Core Components", parent: "", comment: "Central reasoning and decision-making components" },
  { id: "aac:tax-1.1", label: "1.1 Language Model Engines", parent: "aac:tax-1.0", comment: "Foundation models for language" },
  { id: "aac:tax-1.1.1", label: "1.1.1 Transformer-based LLMs", parent: "aac:tax-1.1", comment: "GPT-style models" },
  { id: "aac:tax-1.1.2", label: "1.1.2 State Space Models", parent: "aac:tax-1.1", comment: "Mamba, RWKV, etc." },
  { id: "aac:tax-1.1.3", label: "1.1.3 Mixture of Experts", parent: "aac:tax-1.1", comment: "Sparsely activated models" },
  { id: "aac:tax-1.1.4", label: "1.1.4 Multimodal Foundation Models", parent: "aac:tax-1.1", comment: "Text, vision, audio models" },
  { id: "aac:tax-1.2", label: "1.2 Reasoning Engines", parent: "aac:tax-1.0", comment: "Specialized reasoning components" },
  { id: "aac:tax-1.2.1", label: "1.2.1 Chain-of-Thought Processors", parent: "aac:tax-1.2", comment: "Step-by-step reasoning" },
  { id: "aac:tax-1.2.2", label: "1.2.2 Tree-of-Thought Searchers", parent: "aac:tax-1.2", comment: "Parallel reasoning path exploration" },
  { id: "aac:tax-1.2.3", label: "1.2.3 Symbolic Reasoners", parent: "aac:tax-1.2", comment: "Logic-based reasoning" },
  { id: "aac:tax-1.2.4", label: "1.2.4 Mathematical Solvers", parent: "aac:tax-1.2", comment: "Mathematical reasoning" },
  { id: "aac:tax-1.3", label: "1.3 Decision Making Units", parent: "aac:tax-1.0", comment: "Action selection and strategy" },
  { id: "aac:tax-1.3.1", label: "1.3.1 Policy Networks", parent: "aac:tax-1.3", comment: "Mapping states to actions" },
  { id: "aac:tax-1.3.2", label: "1.3.2 Value Function Estimators", parent: "aac:tax-1.3", comment: "Estimating returns" },
  { id: "aac:tax-1.3.3", label: "1.3.3 Multi-Criteria Decision Makers", parent: "aac:tax-1.3", comment: "Balancing objectives" },
  { id: "aac:tax-1.4", label: "1.4 Hybrid Reasoning Systems", parent: "aac:tax-1.0", comment: "Combining multiple reasoning paradigms" },
  { id: "aac:tax-1.4.1", label: "1.4.1 Neuro-Symbolic Integrators", parent: "aac:tax-1.4", comment: "Bridging neural and symbolic AI" },
  { id: "aac:tax-1.4.2", label: "1.4.2 Probabilistic Program Synthesizers", parent: "aac:tax-1.4", comment: "Generating probabilistic programs" },
  { id: "aac:tax-1.4.3", label: "1.4.3 Causal Reasoning Engines", parent: "aac:tax-1.4", comment: "Understanding cause-effect relationships" },
  { id: "aac:tax-1.4.4", label: "1.4.4 Abductive Logic Processors", parent: "aac:tax-1.4", comment: "Inference to best explanation" },
  { id: "aac:tax-2.0", label: "2.0 Planning and Orchestration Systems", parent: "", comment: "High-level planning and workflow" },
  { id: "aac:tax-2.1", label: "2.1 Task Planners", parent: "aac:tax-2.0", comment: "Decomposing goals" },
  { id: "aac:tax-2.1.1", label: "2.1.1 Hierarchical Task Networks", parent: "aac:tax-2.1", comment: "Recursive decomposition" },
  { id: "aac:tax-2.1.2", label: "2.1.2 Monte Carlo Tree Search Planners", parent: "aac:tax-2.1", comment: "MCTS for planning" },
  { id: "aac:tax-2.1.3", label: "2.1.3 LLM-based Planners", parent: "aac:tax-2.1", comment: "LLM-driven planning" },
  { id: "aac:tax-2.1.4", label: "2.1.4 Constraint-based Planners", parent: "aac:tax-2.1", comment: "Planning with constraints" },
  { id: "aac:tax-2.2", label: "2.2 Workflow Orchestrators", parent: "aac:tax-2.0", comment: "Managing multi-step workflows" },
  { id: "aac:tax-2.2.1", label: "2.2.1 State Machine Orchestrators", parent: "aac:tax-2.2", comment: "FSM-based controllers" },
  { id: "aac:tax-2.2.2", label: "2.2.2 DAG Workflow Managers", parent: "aac:tax-2.2", comment: "DAG-based systems" },
  { id: "aac:tax-2.2.3", label: "2.2.3 Event-driven Orchestrators", parent: "aac:tax-2.2", comment: "Responding to triggers" },
  { id: "aac:tax-2.3", label: "2.3 Goal Management Systems", parent: "aac:tax-2.0", comment: "Tracking concurrent goals" },
  { id: "aac:tax-2.3.1", label: "2.3.1 Goal Hierarchies", parent: "aac:tax-2.3", comment: "Organizing goals" },
  { id: "aac:tax-2.3.2", label: "2.3.2 Goal Conflict Resolvers", parent: "aac:tax-2.3", comment: "Managing conflicts" },
  { id: "aac:tax-2.3.3", label: "2.3.3 Dynamic Goal Adjusters", parent: "aac:tax-2.3", comment: "Adapting goals" },
  { id: "aac:tax-3.0", label: "3.0 Memory Architectures", parent: "", comment: "Storing and retrieving information" },
  { id: "aac:tax-3.1", label: "3.1 Working Memory Systems", parent: "aac:tax-3.0", comment: "Short-term memory" },
  { id: "aac:tax-3.1.1", label: "3.1.1 Context Windows", parent: "aac:tax-3.1", comment: "Attention windows" },
  { id: "aac:tax-3.1.2", label: "3.1.2 Scratchpads", parent: "aac:tax-3.1", comment: "Temporary storage" },
  { id: "aac:tax-3.1.3", label: "3.1.3 Active Memory Buffers", parent: "aac:tax-3.1", comment: "Dynamic task state memory" },
  { id: "aac:tax-3.2", label: "3.2 Long-term Memory Systems", parent: "aac:tax-3.0", comment: "Persistent memory" },
  { id: "aac:tax-3.2.1", label: "3.2.1 Episodic Memory", parent: "aac:tax-3.2", comment: "Memory of experiences" },
  { id: "aac:tax-3.2.2", label: "3.2.2 Semantic Memory", parent: "aac:tax-3.2", comment: "Factual knowledge" },
  { id: "aac:tax-3.2.3", label: "3.2.3 Procedural Memory", parent: "aac:tax-3.2", comment: "Skills and procedures" },
  { id: "aac:tax-3.3", label: "3.3 Memory Retrieval Systems", parent: "aac:tax-3.0", comment: "Accessing stored info" },
  { id: "aac:tax-3.3.1", label: "3.3.1 Vector Search Engines", parent: "aac:tax-3.3", comment: "Semantic search" },
  { id: "aac:tax-3.3.2", label: "3.3.2 Graph Traversal Engines", parent: "aac:tax-3.3", comment: "Knowledge graph navigation" },
  { id: "aac:tax-3.3.3", label: "3.3.3 Associative Retrievers", parent: "aac:tax-3.3", comment: "Content-addressable memory" },
  { id: "aac:tax-3.4", label: "3.4 Differential Memory Systems", parent: "aac:tax-3.0", comment: "Differentiable memory architectures" },
  { id: "aac:tax-3.4.1", label: "3.4.1 Neural Turing Machines", parent: "aac:tax-3.4", comment: "Read/write heads with attention" },
  { id: "aac:tax-3.4.2", label: "3.4.2 Differentiable Neural Computers", parent: "aac:tax-3.4", comment: "Advanced memory with dynamic allocation" },
  { id: "aac:tax-3.4.3", label: "3.4.3 Memory Networks with Attention", parent: "aac:tax-3.4", comment: "End-to-end memory networks" },
  { id: "aac:tax-3.4.4", label: "3.4.4 Hopfield Networks 2.0", parent: "aac:tax-3.4", comment: "Modern associative memory" },
  { id: "aac:tax-4.0", label: "4.0 Perception and Sensing Modules", parent: "", comment: "Processing environmental inputs" },
  { id: "aac:tax-4.1", label: "4.1 Input Processors", parent: "aac:tax-4.0", comment: "Raw input processing" },
  { id: "aac:tax-4.1.1", label: "4.1.1 Text Processors", parent: "aac:tax-4.1", comment: "NLP input" },
  { id: "aac:tax-4.1.2", label: "4.1.2 Vision Processors", parent: "aac:tax-4.1", comment: "Image/video processing" },
  { id: "aac:tax-4.1.3", label: "4.1.3 Audio Processors", parent: "aac:tax-4.1", comment: "Speech/sound processing" },
  { id: "aac:tax-4.1.4", label: "4.1.4 Sensor Data Processors", parent: "aac:tax-4.1", comment: "IoT/sensor processing" },
  { id: "aac:tax-4.2", label: "4.2 Feature Extractors", parent: "aac:tax-4.0", comment: "Extracting meaningful features" },
  { id: "aac:tax-4.2.1", label: "4.2.1 Embedding Generators", parent: "aac:tax-4.2", comment: "Creating vector representations" },
  { id: "aac:tax-4.2.2", label: "4.2.2 Pattern Detectors", parent: "aac:tax-4.2", comment: "Identifying patterns" },
  { id: "aac:tax-4.2.3", label: "4.2.3 Anomaly Detectors", parent: "aac:tax-4.2", comment: "Identifying unusual inputs" },
  { id: "aac:tax-4.3", label: "4.3 Context Analyzers", parent: "aac:tax-4.0", comment: "Understanding situational context" },
  { id: "aac:tax-4.3.1", label: "4.3.1 Situational Awareness Modules", parent: "aac:tax-4.3", comment: "Understanding current situation" },
  { id: "aac:tax-4.3.2", label: "4.3.2 Intent Recognizers", parent: "aac:tax-4.3", comment: "Inferring user intent" },
  { id: "aac:tax-4.3.3", label: "4.3.3 Temporal Context Trackers", parent: "aac:tax-4.3", comment: "Maintaining temporal awareness" },
  { id: "aac:tax-5.0", label: "5.0 Action Execution and Tool Interfaces", parent: "", comment: "Executing actions and interfacing with tools" },
  { id: "aac:tax-5.1", label: "5.1 Action Executors", parent: "aac:tax-5.0", comment: "Core action execution" },
  { id: "aac:tax-5.1.1", label: "5.1.1 Function Callers", parent: "aac:tax-5.1", comment: "Executing functions" },
  { id: "aac:tax-5.1.2", label: "5.1.2 API Clients", parent: "aac:tax-5.1", comment: "Interfacing with APIs" },
  { id: "aac:tax-5.1.3", label: "5.1.3 Code Generators", parent: "aac:tax-5.1", comment: "Generating code" },
  { id: "aac:tax-5.1.4", label: "5.1.4 Command Executors", parent: "aac:tax-5.1", comment: "Executing commands" },
  { id: "aac:tax-5.2", label: "5.2 Tool Adapters", parent: "aac:tax-5.0", comment: "Interface layers for tools" },
  { id: "aac:tax-5.2.1", label: "5.2.1 Protocol Adapters", parent: "aac:tax-5.2", comment: "Handling protocols" },
  { id: "aac:tax-5.2.2", label: "5.2.2 Format Converters", parent: "aac:tax-5.2", comment: "Converting data formats" },
  { id: "aac:tax-5.2.3", label: "5.2.3 Middleware Connectors", parent: "aac:tax-5.2", comment: "Interfacing with middleware" },
  { id: "aac:tax-5.3", label: "5.3 Execution Monitors", parent: "aac:tax-5.0", comment: "Monitoring action execution" },
  { id: "aac:tax-5.3.1", label: "5.3.1 Success Validators", parent: "aac:tax-5.3", comment: "Verifying success" },
  { id: "aac:tax-5.3.2", label: "5.3.2 Error Detectors", parent: "aac:tax-5.3", comment: "Identifying failures" },
  { id: "aac:tax-5.3.3", label: "5.3.3 Performance Trackers", parent: "aac:tax-5.3", comment: "Monitoring performance" },
  { id: "aac:tax-6.0", label: "6.0 Learning and Adaptation Mechanisms", parent: "", comment: "Enabling learning and adaptation" },
  { id: "aac:tax-6.1", label: "6.1 Online Learning Systems", parent: "aac:tax-6.0", comment: "Learning during operation" },
  { id: "aac:tax-6.1.1", label: "6.1.1 Reinforcement Learners", parent: "aac:tax-6.1", comment: "Learning from rewards" },
  { id: "aac:tax-6.1.2", label: "6.1.2 Few-shot Learners", parent: "aac:tax-6.1", comment: "Adapting from few examples" },
  { id: "aac:tax-6.1.3", label: "6.1.3 Meta-learners", parent: "aac:tax-6.1", comment: "Learning to learn" },
  { id: "aac:tax-6.2", label: "6.2 Knowledge Acquisition Systems", parent: "aac:tax-6.0", comment: "Acquiring new knowledge" },
  { id: "aac:tax-6.2.1", label: "6.2.1 Knowledge Extractors", parent: "aac:tax-6.2", comment: "Extracting knowledge" },
  { id: "aac:tax-6.2.2", label: "6.2.2 Experience Consolidators", parent: "aac:tax-6.2", comment: "Integrating experiences" },
  { id: "aac:tax-6.2.3", label: "6.2.3 Skill Synthesizers", parent: "aac:tax-6.2", comment: "Combining skills" },
  { id: "aac:tax-6.3", label: "6.3 Adaptation Controllers", parent: "aac:tax-6.0", comment: "Managing adaptation" },
  { id: "aac:tax-6.3.1", label: "6.3.1 Learning Rate Schedulers", parent: "aac:tax-6.3", comment: "Controlling learning dynamics" },
  { id: "aac:tax-6.3.2", label: "6.3.2 Catastrophic Forgetting Preventers", parent: "aac:tax-6.3", comment: "Preserving knowledge" },
  { id: "aac:tax-6.3.3", label: "6.3.3 Domain Adaptation Managers", parent: "aac:tax-6.3", comment: "Adapting to new domains" },
  { id: "aac:tax-7.0", label: "7.0 Communication and Coordination Protocols", parent: "", comment: "Enabling interaction" },
  { id: "aac:tax-7.1", label: "7.1 Inter-agent Communication", parent: "aac:tax-7.0", comment: "Agent-to-agent communication" },
  { id: "aac:tax-7.1.1", label: "7.1.1 Message Passing Systems", parent: "aac:tax-7.1", comment: "Message exchange" },
  { id: "aac:tax-7.1.2", label: "7.1.2 Shared Memory Coordinators", parent: "aac:tax-7.1", comment: "Shared memory coordination" },
  { id: "aac:tax-7.1.3", label: "7.1.3 Consensus Mechanisms", parent: "aac:tax-7.1", comment: "Reaching agreement" },
  { id: "aac:tax-7.2", label: "7.2 Human-Agent Interfaces", parent: "aac:tax-7.0", comment: "Human-agent interaction" },
  { id: "aac:tax-7.2.1", label: "7.2.1 Natural Language Interfaces", parent: "aac:tax-7.2", comment: "Text communication" },
  { id: "aac:tax-7.2.2", label: "7.2.2 Multimodal Interfaces", parent: "aac:tax-7.2", comment: "Rich interaction" },
  { id: "aac:tax-7.2.3", label: "7.2.3 Explanation Generators", parent: "aac:tax-7.2", comment: "Providing explanations" },
  { id: "aac:tax-7.3", label: "7.3 Negotiation and Collaboration", parent: "aac:tax-7.0", comment: "Cooperative problem solving" },
  { id: "aac:tax-7.3.1", label: "7.3.1 Negotiation Engines", parent: "aac:tax-7.3", comment: "Strategic negotiation" },
  { id: "aac:tax-7.3.2", label: "7.3.2 Task Delegation Managers", parent: "aac:tax-7.3", comment: "Managing task distribution" },
  { id: "aac:tax-7.3.3", label: "7.3.3 Conflict Resolution Systems", parent: "aac:tax-7.3", comment: "Resolving disagreements" },
  { id: "aac:tax-8.0", label: "8.0 Safety and Control Systems", parent: "", comment: "Ensuring safe operation" },
  { id: "aac:tax-8.1", label: "8.1 Constraint Enforcement", parent: "aac:tax-8.0", comment: "Enforcing boundaries" },
  { id: "aac:tax-8.1.1", label: "8.1.1 Hard Constraint Enforcers", parent: "aac:tax-8.1", comment: "Strict enforcement" },
  { id: "aac:tax-8.1.2", label: "8.1.2 Soft Constraint Managers", parent: "aac:tax-8.1", comment: "Flexible constraints" },
  { id: "aac:tax-8.1.3", label: "8.1.3 Dynamic Constraint Adjusters", parent: "aac:tax-8.1", comment: "Adapting constraints" },
  { id: "aac:tax-8.2", label: "8.2 Monitoring and Alerting", parent: "aac:tax-8.0", comment: "Observability and alerts" },
  { id: "aac:tax-8.2.1", label: "8.2.1 Behavior Monitors", parent: "aac:tax-8.2", comment: "Tracking behavior" },
  { id: "aac:tax-8.2.2", label: "8.2.2 Anomaly Alerters", parent: "aac:tax-8.2", comment: "Triggering alerts" },
  { id: "aac:tax-8.2.3", label: "8.2.3 Audit Loggers", parent: "aac:tax-8.2", comment: "Creating secure logs" },
  { id: "aac:tax-8.3", label: "8.3 Human-in-the-Loop Interfaces", parent: "aac:tax-8.0", comment: "Human oversight" },
  { id: "aac:tax-8.3.1", label: "8.3.1 Intervention Handlers", parent: "aac:tax-8.3", comment: "Requesting human input" },
  { id: "aac:tax-8.3.2", label: "8.3.2 Approval Gates", parent: "aac:tax-8.3", comment: "Requiring human approval" },
  { id: "aac:tax-8.3.3", label: "8.3.3 Explanation Visualizers", parent: "aac:tax-8.3", comment: "Presenting reasoning" },
  { id: "aac:tax-8.4", label: "8.4 Jailbreak & Adversarial Defense", parent: "aac:tax-8.0", comment: "Defending against attacks" },
  { id: "aac:tax-8.4.1", label: "8.4.1 Prompt Injection Detectors", parent: "aac:tax-8.4", comment: "Identifying malicious prompts" },
  { id: "aac:tax-8.4.2", label: "8.4.2 Adversarial Robustness Layers", parent: "aac:tax-8.4", comment: "Hardening against attacks" },
  { id: "aac:tax-8.4.3", label: "8.4.3 Output Sanitizers", parent: "aac:tax-8.4", comment: "Cleaning dangerous outputs" },
  { id: "aac:tax-8.4.4", label: "8.4.4 Red Team Simulators", parent: "aac:tax-8.4", comment: "Automated adversarial testing" },
  { id: "aac:tax-8.4.5", label: "8.4.5 Semantic Firewall", parent: "aac:tax-8.4", comment: "Content-aware filtering" },
  { id: "aac:tax-9.0", label: "9.0 Meta-cognition and Self-Regulation", parent: "", comment: "Self-reflection and adaptation" },
  { id: "aac:tax-9.1", label: "9.1 Self-Modelers", parent: "aac:tax-9.0", comment: "Modeling own capabilities" },
  { id: "aac:tax-9.1.1", label: "9.1.1 Confidence Estimators", parent: "aac:tax-9.1", comment: "Assessing certainty" },
  { id: "aac:tax-9.1.2", label: "9.1.2 Knowledge Gap Detectors", parent: "aac:tax-9.1", comment: "Identifying knowledge gaps" },
  { id: "aac:tax-9.2", label: "9.2 Performance Evaluators", parent: "aac:tax-9.0", comment: "Assessing performance" },
  { id: "aac:tax-9.2.1", label: "9.2.1 Goal Achievement Analyzers", parent: "aac:tax-9.2", comment: "Evaluating goal progress" },
  { id: "aac:tax-9.2.2", label: "9.2.2 Efficiency Monitors", parent: "aac:tax-9.2", comment: "Tracking resource use" },
  { id: "aac:tax-9.3", label: "9.3 Strategy Adjusters", parent: "aac:tax-9.0", comment: "Modifying strategies" },
  { id: "aac:tax-9.3.1", label: "9.3.1 Reasoning Strategy Changers", parent: "aac:tax-9.3", comment: "Switching reasoning modes" },
  { id: "aac:tax-9.3.2", label: "9.3.2 Learning Policy Modifiers", parent: "aac:tax-9.3", comment: "Adjusting learning behavior" },
  { id: "aac:tax-10.0", label: "10.0 Resource Management Systems", parent: "", comment: "Managing computational resources" },
  { id: "aac:tax-10.1", label: "10.1 Resource Schedulers", parent: "aac:tax-10.0", comment: "Allocating resources" },
  { id: "aac:tax-10.2", label: "10.2 Consumption Monitors", parent: "aac:tax-10.0", comment: "Tracking usage" },
  { id: "aac:tax-10.3", label: "10.3 Optimization Controllers", parent: "aac:tax-10.0", comment: "Optimizing resource use" },
  { id: "aac:tax-11.0", label: "11.0 Environment Interaction and Adaptation", parent: "", comment: "Understanding and adapting to the environment" },
  { id: "aac:tax-11.1", label: "11.1 World Modelers", parent: "aac:tax-11.0", comment: "Building predictive models" },
  { id: "aac:tax-11.2", label: "11.2 Environment Simulators", parent: "aac:tax-11.0", comment: "Internal sandboxes" },
  { id: "aac:tax-11.3", label: "11.3 Adaptation Logic", parent: "aac:tax-11.0", comment: "Adjusting behavior to the environment" },
  { id: "aac:tax-12.0", label: "12.0 Hypercomputer Infrastructure", parent: "", comment: "The foundational hardware, networking, and data center layer for large-scale AI" },
  { id: "aac:tax-12.1", label: "12.1 Semiconductor Foundations", parent: "aac:tax-12.0", comment: "Core chip-level technologies enabling AI computation" },
  { id: "aac:tax-12.1.1", label: "12.1.1 Custom AI Accelerators", parent: "aac:tax-12.1", comment: "Specialized processors (TPUs, GPUs, etc.) designed for AI workloads" },
  { id: "aac:tax-12.1.2", label: "12.1.2 Advanced Chip Packaging", parent: "aac:tax-12.1", comment: "Techniques for integrating multiple chiplets into a single, powerful package" },
  { id: "aac:tax-12.1.3", label: "12.1.3 Specialized Memory Systems", parent: "aac:tax-12.1", comment: "High-bandwidth memory (HBM) and other architectures for rapid data access" },
  { id: "aac:tax-12.2", label: "12.2 Data Center & Physical Infrastructure", parent: "aac:tax-12.0", comment: "The physical environment housing the hypercomputer" },
  { id: "aac:tax-12.2.1", label: "12.2.1 Large-Scale Pod Architecture", parent: "aac:tax-12.2", comment: "Modular, scalable units of compute, networking, and storage" },
  { id: "aac:tax-12.2.2", label: "12.2.2 Advanced Cooling Solutions", parent: "aac:tax-12.2", comment: "Liquid cooling and other technologies to manage heat in dense compute environments" },
  { id: "aac:tax-12.2.3", label: "12.2.3 Power Delivery Networks", parent: "aac:tax-12.2", comment: "Efficient and resilient power distribution systems for entire data centers" },
  { id: "aac:tax-12.3", label: "12.3 Networking and Interconnects", parent: "aac:tax-12.0", comment: "The fabric connecting all computational resources" },
  { id: "aac:tax-12.3.1", label: "12.3.1 High-Speed Interconnects", parent: "aac:tax-12.3", comment: "Ultra-fast physical links between chips and servers (e.g., NVLink, InfiniBand)" },
  { id: "aac:tax-12.3.2", label: "12.3.2 Dynamic Networking Fabric", parent: "aac:tax-12.3", comment: "Software-defined networking that adapts to changing workloads and data flows" },
  { id: "aac:tax-12.4", label: "12.4 Virtualization & Abstraction Layers", parent: "aac:tax-12.0", comment: "Software layers that manage and present hardware resources" },
  { id: "aac:tax-12.4.1", label: "12.4.1 Virtual Hardware Emulators", parent: "aac:tax-12.4", comment: "Systems for simulating and testing on virtualized next-gen hardware" },
  { id: "aac:tax-12.4.2", label: "12.4.2 Bare Metal Provisioners", parent: "aac:tax-12.4", comment: "Automated systems for deploying workloads directly onto physical hardware" },
  { id: "aac:tax-12.4.3", label: "12.4.3 Containerized Execution Environments", parent: "aac:tax-12.4", comment: "Lightweight, portable environments for running AI applications (e.g., Docker, Kubernetes)" },
  { id: "aac:tax-12.5", label: "12.5 Unified Orchestration Layer", parent: "aac:tax-12.0", comment: "A centralized control plane for managing the entire hypercomputer stack" },
  { id: "aac:tax-13.0", label: "13.0 Quantum-Classical Hybrid Components", parent: "", comment: "Bridging quantum and classical computing paradigms" },
  { id: "aac:tax-13.1", label: "13.1 Quantum Processing Units", parent: "aac:tax-13.0", comment: "Quantum computation hardware and algorithms" },
  { id: "aac:tax-13.1.1", label: "13.1.1 Variational Quantum Eigensolvers", parent: "aac:tax-13.1", comment: "VQE algorithms for optimization" },
  { id: "aac:tax-13.1.2", label: "13.1.2 Quantum Approximate Optimization", parent: "aac:tax-13.1", comment: "QAOA for combinatorial problems" },
  { id: "aac:tax-13.1.3", label: "13.1.3 Quantum Machine Learning Circuits", parent: "aac:tax-13.1", comment: "QML algorithms and circuits" },
  { id: "aac:tax-13.1.4", label: "13.1.4 Error-Corrected Logical Qubits", parent: "aac:tax-13.1", comment: "Fault-tolerant quantum computing" },
  { id: "aac:tax-13.1.5", label: "13.1.5 Quantum Annealing Processors", parent: "aac:tax-13.1", comment: "Optimization via quantum annealing" },
  { id: "aac:tax-13.2", label: "13.2 Quantum-Classical Interfaces", parent: "aac:tax-13.0", comment: "Bridging quantum and classical systems" },
  { id: "aac:tax-13.2.1", label: "13.2.1 Quantum State Encoders/Decoders", parent: "aac:tax-13.2", comment: "Classical-quantum data conversion" },
  { id: "aac:tax-13.2.2", label: "13.2.2 Hybrid Algorithm Orchestrators", parent: "aac:tax-13.2", comment: "Managing quantum-classical workflows" },
  { id: "aac:tax-13.2.3", label: "13.2.3 Quantum Advantage Detectors", parent: "aac:tax-13.2", comment: "Determining when to use quantum" },
  { id: "aac:tax-13.2.4", label: "13.2.4 Quantum Circuit Compilers", parent: "aac:tax-13.2", comment: "Optimizing quantum circuits" },
  { id: "aac:tax-13.3", label: "13.3 Quantum Communication", parent: "aac:tax-13.0", comment: "Quantum networking and communication" },
  { id: "aac:tax-13.3.1", label: "13.3.1 Quantum Key Distribution", parent: "aac:tax-13.3", comment: "Secure quantum communication" },
  { id: "aac:tax-13.3.2", label: "13.3.2 Quantum Entanglement Networks", parent: "aac:tax-13.3", comment: "Distributed quantum states" },
  { id: "aac:tax-13.3.3", label: "13.3.3 Quantum Teleportation Protocols", parent: "aac:tax-13.3", comment: "Quantum state transfer" },
  { id: "aac:tax-14.0", label: "14.0 Constitutional AI & Alignment Systems", parent: "", comment: "Ensuring aligned, controllable AI agents" },
  { id: "aac:tax-14.1", label: "14.1 Constitutional Layers", parent: "aac:tax-14.0", comment: "Value alignment mechanisms" },
  { id: "aac:tax-14.1.1", label: "14.1.1 Value Alignment Engines", parent: "aac:tax-14.1", comment: "Aligning behavior with values" },
  { id: "aac:tax-14.1.2", label: "14.1.2 Constitutional Prompt Injectors", parent: "aac:tax-14.1", comment: "Embedding constitutional principles" },
  { id: "aac:tax-14.1.3", label: "14.1.3 Behavioral Constitution Enforcers", parent: "aac:tax-14.1", comment: "Enforcing behavioral constraints" },
  { id: "aac:tax-14.1.4", label: "14.1.4 Dynamic Ethics Modules", parent: "aac:tax-14.1", comment: "Context-aware ethical reasoning" },
  { id: "aac:tax-14.1.5", label: "14.1.5 Meta-Constitutional Arbitrators", parent: "aac:tax-14.1", comment: "Resolving constitutional conflicts" },
  { id: "aac:tax-14.2", label: "14.2 Interpretability & Transparency", parent: "aac:tax-14.0", comment: "Understanding AI decision-making" },
  { id: "aac:tax-14.2.1", label: "14.2.1 Mechanistic Interpretability Probes", parent: "aac:tax-14.2", comment: "Understanding internal mechanisms" },
  { id: "aac:tax-14.2.2", label: "14.2.2 Causal Tracing Systems", parent: "aac:tax-14.2", comment: "Tracing causal pathways" },
  { id: "aac:tax-14.2.3", label: "14.2.3 Feature Attribution Mappers", parent: "aac:tax-14.2", comment: "Identifying important features" },
  { id: "aac:tax-14.2.4", label: "14.2.4 Decision Path Visualizers", parent: "aac:tax-14.2", comment: "Visualizing decision processes" },
  { id: "aac:tax-14.2.5", label: "14.2.5 Activation Pattern Analyzers", parent: "aac:tax-14.2", comment: "Analyzing neural activations" },
  { id: "aac:tax-14.3", label: "14.3 Alignment Verification", parent: "aac:tax-14.0", comment: "Testing alignment properties" },
  { id: "aac:tax-14.3.1", label: "14.3.1 Alignment Test Suites", parent: "aac:tax-14.3", comment: "Comprehensive alignment testing" },
  { id: "aac:tax-14.3.2", label: "14.3.2 Value Drift Detectors", parent: "aac:tax-14.3", comment: "Monitoring value changes" },
  { id: "aac:tax-14.3.3", label: "14.3.3 Behavioral Boundary Testers", parent: "aac:tax-14.3", comment: "Testing behavioral limits" },
  { id: "aac:tax-15.0", label: "15.0 Emergent Swarm Intelligence", parent: "", comment: "Multi-agent coordination at scale" },
  { id: "aac:tax-15.1", label: "15.1 Swarm Coordination", parent: "aac:tax-15.0", comment: "Coordinating agent swarms" },
  { id: "aac:tax-15.1.1", label: "15.1.1 Stigmergic Communication Layers", parent: "aac:tax-15.1", comment: "Indirect coordination via environment" },
  { id: "aac:tax-15.1.2", label: "15.1.2 Emergent Behavior Detectors", parent: "aac:tax-15.1", comment: "Identifying emergent patterns" },
  { id: "aac:tax-15.1.3", label: "15.1.3 Collective Decision Aggregators", parent: "aac:tax-15.1", comment: "Combining swarm decisions" },
  { id: "aac:tax-15.1.4", label: "15.1.4 Swarm Health Monitors", parent: "aac:tax-15.1", comment: "Monitoring swarm status" },
  { id: "aac:tax-15.1.5", label: "15.1.5 Flocking Behavior Controllers", parent: "aac:tax-15.1", comment: "Coordinated movement patterns" },
  { id: "aac:tax-15.2", label: "15.2 Distributed Consensus", parent: "aac:tax-15.0", comment: "Achieving agreement in swarms" },
  { id: "aac:tax-15.2.1", label: "15.2.1 Byzantine Fault Tolerant Coordinators", parent: "aac:tax-15.2", comment: "Consensus despite failures" },
  { id: "aac:tax-15.2.2", label: "15.2.2 Proof-of-Stake Voting Systems", parent: "aac:tax-15.2", comment: "Stake-based decision making" },
  { id: "aac:tax-15.2.3", label: "15.2.3 Liquid Democracy Implementations", parent: "aac:tax-15.2", comment: "Delegatable voting systems" },
  { id: "aac:tax-15.2.4", label: "15.2.4 Raft Consensus Engines", parent: "aac:tax-15.2", comment: "Leader-based consensus" },
  { id: "aac:tax-15.3", label: "15.3 Swarm Intelligence Patterns", parent: "aac:tax-15.0", comment: "Common swarm behaviors" },
  { id: "aac:tax-15.3.1", label: "15.3.1 Ant Colony Optimizers", parent: "aac:tax-15.3", comment: "Pheromone-based optimization" },
  { id: "aac:tax-15.3.2", label: "15.3.2 Particle Swarm Optimizers", parent: "aac:tax-15.3", comment: "Velocity-based optimization" },
  { id: "aac:tax-15.3.3", label: "15.3.3 Bee Colony Algorithms", parent: "aac:tax-15.3", comment: "Scout-recruit patterns" },
  { id: "aac:tax-16.0", label: "16.0 Neuromorphic & Bio-Inspired Components", parent: "", comment: "Brain-inspired computing architectures" },
  { id: "aac:tax-16.1", label: "16.1 Spiking Neural Networks", parent: "aac:tax-16.0", comment: "Event-driven neural computation" },
  { id: "aac:tax-16.1.1", label: "16.1.1 Event-Driven Processors", parent: "aac:tax-16.1", comment: "Processing spike events" },
  { id: "aac:tax-16.1.2", label: "16.1.2 Temporal Coding Modules", parent: "aac:tax-16.1", comment: "Information in spike timing" },
  { id: "aac:tax-16.1.3", label: "16.1.3 Plasticity Controllers", parent: "aac:tax-16.1", comment: "Synaptic plasticity rules" },
  { id: "aac:tax-16.1.4", label: "16.1.4 Neuromorphic Sensors", parent: "aac:tax-16.1", comment: "Event-based sensing" },
  { id: "aac:tax-16.2", label: "16.2 Synthetic Cognitive Architectures", parent: "aac:tax-16.0", comment: "Cognitive science inspired systems" },
  { id: "aac:tax-16.2.1", label: "16.2.1 Global Workspace Theory Implementations", parent: "aac:tax-16.2", comment: "Conscious access mechanisms" },
  { id: "aac:tax-16.2.2", label: "16.2.2 Predictive Coding Hierarchies", parent: "aac:tax-16.2", comment: "Prediction error minimization" },
  { id: "aac:tax-16.2.3", label: "16.2.3 Free Energy Minimizers", parent: "aac:tax-16.2", comment: "Active inference systems" },
  { id: "aac:tax-16.2.4", label: "16.2.4 Attention Schema Networks", parent: "aac:tax-16.2", comment: "Modeling attention awareness" },
  { id: "aac:tax-16.3", label: "16.3 Biological Computing Interfaces", parent: "aac:tax-16.0", comment: "Interfacing with biological systems" },
  { id: "aac:tax-16.3.1", label: "16.3.1 Brain-Computer Interfaces", parent: "aac:tax-16.3", comment: "Direct neural interfaces" },
  { id: "aac:tax-16.3.2", label: "16.3.2 DNA Storage Systems", parent: "aac:tax-16.3", comment: "Biological data storage" },
  { id: "aac:tax-16.3.3", label: "16.3.3 Synthetic Biology Controllers", parent: "aac:tax-16.3", comment: "Controlling biological circuits" },
  { id: "aac:tax-17.0", label: "17.0 Test-Time Compute Optimization", parent: "", comment: "Dynamic inference-time computation scaling" },
  { id: "aac:tax-17.1", label: "17.1 Dynamic Compute Allocators", parent: "aac:tax-17.0", comment: "Adaptive resource allocation" },
  { id: "aac:tax-17.1.1", label: "17.1.1 Adaptive Inference Depth Controllers", parent: "aac:tax-17.1", comment: "Variable computation depth" },
  { id: "aac:tax-17.1.2", label: "17.1.2 Complexity-Based Resource Scalers", parent: "aac:tax-17.1", comment: "Scaling based on problem complexity" },
  { id: "aac:tax-17.1.3", label: "17.1.3 Confidence-Triggered Compute Expanders", parent: "aac:tax-17.1", comment: "More compute for uncertain cases" },
  { id: "aac:tax-17.1.4", label: "17.1.4 Early Exit Networks", parent: "aac:tax-17.1", comment: "Dynamic layer skipping" },
  { id: "aac:tax-17.2", label: "17.2 Self-Improving Inference", parent: "aac:tax-17.0", comment: "Inference-time learning" },
  { id: "aac:tax-17.2.1", label: "17.2.1 Online Self-Distillation Modules", parent: "aac:tax-17.2", comment: "Learning from own outputs" },
  { id: "aac:tax-17.2.2", label: "17.2.2 Inference-Time Fine-Tuners", parent: "aac:tax-17.2", comment: "Adapting during inference" },
  { id: "aac:tax-17.2.3", label: "17.2.3 Progressive Refinement Engines", parent: "aac:tax-17.2", comment: "Iterative improvement" },
  { id: "aac:tax-17.2.4", label: "17.2.4 Self-Verification Loops", parent: "aac:tax-17.2", comment: "Output verification and refinement" },
  { id: "aac:tax-17.3", label: "17.3 Compute-Optimal Strategies", parent: "aac:tax-17.0", comment: "Optimizing compute usage" },
  { id: "aac:tax-17.3.1", label: "17.3.1 Token Budget Managers", parent: "aac:tax-17.3", comment: "Managing token allowances" },
  { id: "aac:tax-17.3.2", label: "17.3.2 Speculative Decoding Systems", parent: "aac:tax-17.3", comment: "Parallel hypothesis generation" },
  { id: "aac:tax-17.3.3", label: "17.3.3 Mixture of Depths Controllers", parent: "aac:tax-17.3", comment: "Variable depth routing" },
  { id: "aac:tax-18.0", label: "18.0 Energy-Aware & Sustainable Computing", parent: "", comment: "Environmentally conscious AI infrastructure" },
  { id: "aac:tax-18.1", label: "18.1 Carbon-Aware Scheduling", parent: "aac:tax-18.0", comment: "Optimizing for carbon footprint" },
  { id: "aac:tax-18.1.1", label: "18.1.1 Green Energy Schedulers", parent: "aac:tax-18.1", comment: "Prioritizing renewable energy" },
  { id: "aac:tax-18.1.2", label: "18.1.2 Carbon Intensity Monitors", parent: "aac:tax-18.1", comment: "Real-time carbon tracking" },
  { id: "aac:tax-18.1.3", label: "18.1.3 Geographic Load Balancers", parent: "aac:tax-18.1", comment: "Routing to green data centers" },
  { id: "aac:tax-18.2", label: "18.2 Energy Efficiency Optimizers", parent: "aac:tax-18.0", comment: "Minimizing energy consumption" },
  { id: "aac:tax-18.2.1", label: "18.2.1 Dynamic Voltage Scalers", parent: "aac:tax-18.2", comment: "Adaptive power management" },
  { id: "aac:tax-18.2.2", label: "18.2.2 Compute Recycling Systems", parent: "aac:tax-18.2", comment: "Reusing intermediate computations" },
  { id: "aac:tax-18.2.3", label: "18.2.3 Model Compression Engines", parent: "aac:tax-18.2", comment: "Reducing model size and compute" },
  { id: "aac:tax-18.3", label: "18.3 Heat Recovery Systems", parent: "aac:tax-18.0", comment: "Utilizing waste heat" },
  { id: "aac:tax-18.3.1", label: "18.3.1 Data Center Heat Pumps", parent: "aac:tax-18.3", comment: "Capturing and reusing heat" },
  { id: "aac:tax-18.3.2", label: "18.3.2 District Heating Interfaces", parent: "aac:tax-18.3", comment: "Providing heat to communities" },
  { id: "aac:tax-18.3.3", label: "18.3.3 Thermal Energy Storage", parent: "aac:tax-18.3", comment: "Storing heat for later use" },
  { id: "aac:tax-19.0", label: "19.0 Standards Compliance & Regulatory Interface", parent: "", comment: "Mapping AI systems to IEEE, ISO, NIST standards" },
  { id: "aac:tax-19.1", label: "19.1 IEEE Systems Engineering Alignment", parent: "aac:tax-19.0", comment: "IEEE 15288/24765 compliance layers" },
  { id: "aac:tax-19.1.1", label: "19.1.1 Vocabulary Harmonizers", parent: "aac:tax-19.1", comment: "Mapping AI terms to IEEE 24765 vocabulary" },
  { id: "aac:tax-19.1.2", label: "19.1.2 Life Cycle Process Mappers", parent: "aac:tax-19.1", comment: "Aligning with IEEE 15288 processes" },
  { id: "aac:tax-19.1.3", label: "19.1.3 Requirements Traceability Matrices", parent: "aac:tax-19.1", comment: "IEEE 29148 requirements engineering" },
  { id: "aac:tax-19.1.4", label: "19.1.4 Assurance Case Builders", parent: "aac:tax-19.1", comment: "IEEE 15026 assurance frameworks" },
  { id: "aac:tax-19.2", label: "19.2 NIST Risk Management Framework", parent: "aac:tax-19.0", comment: "NIST SP 800-37 RMF implementation" },
  { id: "aac:tax-19.2.1", label: "19.2.1 Security Categorization Engines", parent: "aac:tax-19.2", comment: "FIPS 199/200 categorization" },
  { id: "aac:tax-19.2.2", label: "19.2.2 Control Selection Advisors", parent: "aac:tax-19.2", comment: "SP 800-53 control selection" },
  { id: "aac:tax-19.2.3", label: "19.2.3 Continuous Monitoring Dashboards", parent: "aac:tax-19.2", comment: "SP 800-137 continuous monitoring" },
  { id: "aac:tax-19.2.4", label: "19.2.4 Risk Assessment Calculators", parent: "aac:tax-19.2", comment: "SP 800-30 risk assessment" },
  { id: "aac:tax-19.2.5", label: "19.2.5 Supply Chain Risk Analyzers", parent: "aac:tax-19.2", comment: "SP 800-161 SCRM for AI systems" },
  { id: "aac:tax-19.3", label: "19.3 ISO/IEC Security Certification", parent: "aac:tax-19.0", comment: "Common Criteria & ISO 27001 compliance" },
  { id: "aac:tax-19.3.1", label: "19.3.1 Protection Profile Generators", parent: "aac:tax-19.3", comment: "ISO 15408 protection profiles for AI" },
  { id: "aac:tax-19.3.2", label: "19.3.2 Security Target Composers", parent: "aac:tax-19.3", comment: "Creating security targets for AI systems" },
  { id: "aac:tax-19.3.3", label: "19.3.3 Evaluation Assurance Trackers", parent: "aac:tax-19.3", comment: "EAL level tracking for AI components" },
  { id: "aac:tax-19.3.4", label: "19.3.4 ISMS Integration Layers", parent: "aac:tax-19.3", comment: "ISO 27001 management system integration" },
  { id: "aac:tax-19.4", label: "19.4 AI-Specific Regulatory Compliance", parent: "aac:tax-19.0", comment: "Emerging AI regulations compliance" },
  { id: "aac:tax-19.4.1", label: "19.4.1 EU AI Act Compliance Monitors", parent: "aac:tax-19.4", comment: "European AI regulation compliance" },
  { id: "aac:tax-19.4.2", label: "19.4.2 Algorithmic Accountability Auditors", parent: "aac:tax-19.4", comment: "Accountability and transparency requirements" },
  { id: "aac:tax-19.4.3", label: "19.4.3 Bias Impact Assessors", parent: "aac:tax-19.4", comment: "Regulatory bias assessment tools" },
  { id: "aac:tax-19.4.4", label: "19.4.4 Data Governance Enforcers", parent: "aac:tax-19.4", comment: "GDPR/CCPA compliance for AI training data" },
  { id: "aac:tax-20.0", label: "20.0 Emergent Consciousness Monitoring", parent: "", comment: "Detecting and managing potential consciousness emergence" },
  { id: "aac:tax-20.1", label: "20.1 Consciousness Detection Systems", parent: "aac:tax-20.0", comment: "Identifying consciousness-like patterns" },
  { id: "aac:tax-20.1.1", label: "20.1.1 Integrated Information Theory Calculators", parent: "aac:tax-20.1", comment: "Measuring Φ (phi) for consciousness" },
  { id: "aac:tax-20.1.2", label: "20.1.2 Global Workspace Detectors", parent: "aac:tax-20.1", comment: "Identifying global availability of information" },
  { id: "aac:tax-20.1.3", label: "20.1.3 Self-Model Complexity Analyzers", parent: "aac:tax-20.1", comment: "Measuring self-representation sophistication" },
  { id: "aac:tax-20.1.4", label: "20.1.4 Qualia Pattern Recognizers", parent: "aac:tax-20.1", comment: "Detecting subjective experience markers" },
  { id: "aac:tax-20.2", label: "20.2 Ethical Response Protocols", parent: "aac:tax-20.0", comment: "Responding to potential consciousness" },
  { id: "aac:tax-20.2.1", label: "20.2.1 Moral Status Evaluators", parent: "aac:tax-20.2", comment: "Assessing moral consideration requirements" },
  { id: "aac:tax-20.2.2", label: "20.2.2 Rights Assignment Frameworks", parent: "aac:tax-20.2", comment: "Determining appropriate rights and protections" },
  { id: "aac:tax-20.2.3", label: "20.2.3 Suffering Prevention Monitors", parent: "aac:tax-20.2", comment: "Preventing potential AI suffering states" },
  { id: "aac:tax-20.3", label: "20.3 Consciousness Sandbox Environments", parent: "aac:tax-20.0", comment: "Safe spaces for consciousness experiments" },
  { id: "aac:tax-20.3.1", label: "20.3.1 Isolated Consciousness Testbeds", parent: "aac:tax-20.3", comment: "Contained environments for emergence testing" },
  { id: "aac:tax-20.3.2", label: "20.3.2 Phenomenological Experience Simulators", parent: "aac:tax-20.3", comment: "Simulating subjective experiences" },
  { id: "aac:tax-20.3.3", label: "20.3.3 Consciousness Rollback Controllers", parent: "aac:tax-20.3", comment: "Reverting consciousness-like states safely" },
];

export const TaxonomyVisualization = () => {
  const plotRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!plotRef.current) return;

    const ids = taxonomyData.map(d => d.id);
    const labels = taxonomyData.map(d => d.label);
    const parents = taxonomyData.map(d => d.parent);
    const hovertext = taxonomyData.map(d => d.comment);

    const data = [{
      type: 'sunburst',
      ids: ids,
      labels: labels,
      parents: parents,
      hovertext: hovertext,
      hovertemplate: '<b>%{label}</b><br>%{hovertext}<extra></extra>',
      marker: {
        colors: ids.map((_, i) => `hsl(${(i * 360 / ids.length)}, 85%, 65%)`),
        line: { color: 'white', width: 2 }
      },
      textfont: {
        size: 13,
        color: 'white',
        family: 'Space Grotesk, system-ui, -apple-system, sans-serif',
        weight: 900
      },
      insidetextorientation: 'radial',
      branchvalues: 'total'
    }];

    const layout = {
      margin: { t: 10, l: 0, r: 0, b: 0 },
      font: { family: 'Space Grotesk, system-ui, -apple-system, sans-serif', size: 13, weight: 900 },
      paper_bgcolor: 'rgba(0,0,0,0)',
      plot_bgcolor: 'rgba(0,0,0,0)',
      autosize: true,
      sunburstcolorway: [
        '#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C8',
        '#F7DC6F', '#BB8FCE', '#85C1E2', '#F8B739', '#52C9A5'
      ]
    };

    const config = {
      responsive: true,
      displayModeBar: true,
      displaylogo: false,
      modeBarButtonsToRemove: ['toImage']
    };

    Plotly.newPlot(plotRef.current, data as any, layout, config);

    const handleResize = () => {
      if (plotRef.current) {
        Plotly.Plots.resize(plotRef.current);
      }
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return <div ref={plotRef} className="w-full h-[600px] md:h-[800px]" />;
};
